In [2]:
import numpy as np

In [23]:
import numpy as np

class LogisticRegression:
    def __init__(self, learning_rate=0.1, n_iter=1000):
        self.bias = None
        self.weights = None
        self.lr = learning_rate
        self.n_iter = n_iter

    def _sigmoid(self, z):
        return 1 / (1 + np.exp(-z))

    def fit(self, X, y):
        m, n = X.shape

        self.bias = 0
        self.weights = np.zeros(n)

        for _ in range(self.n_iter):
            z = self.bias + np.dot(X, self.weights)
            y_pred = self._sigmoid(z)

            db = (1 / m) * np.sum(y_pred - y)
            dw = (1 / m) * np.dot(X.T, (y_pred - y))

            self.bias -= self.lr * db
            self.weights -= self.lr * dw

    def get_probabilities(self, X):
        z = self.bias + np.dot(X, self.weights)
        return self._sigmoid(z)

    def predict(self, X, threshold=0.5):
        probabilities = self.get_probabilities(X)
        return (probabilities >= threshold).astype(int)
        

In [4]:
arr = np.array([0.67, 0.99, 0.23])
(arr >= 0.5).astype(int)

array([1, 1, 0])

In [27]:
X = np.array([[1,2],[2,3],[3,4],[4,5]])
y = np.array([0, 0, 1, 1])

model = LogisticRegression()
model.fit(X, y)

y_pred = model.predict(X)
print(y_pred)
print(model.get_probabilities(X))

[0 0 1 1]
[0.02871674 0.26532955 0.81521201 0.98178143]
