In [1]:
import numpy as np
import time

In [3]:
arr = np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [9]:
#comparing time

size = 100_000_000

py_list = list(range(size))

#python list
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"It satrted from {start} and ended at {end} , took {end - start} seconds")


#numpy array
np_arr = np.array(sq_list)
start = time.time()
sq_array = np_arr ** 2
end = time.time()
print(f"It satrted from {start} and ended at {end} , took {end - start} seconds")

It satrted from 1776348693.2388434 and ended at 1776348717.1757505 , took 23.936907052993774 seconds
It satrted from 1776348738.2458632 and ended at 1776348738.8906941 , took 0.6448309421539307 seconds


In [11]:
#comparing size

import sys

print(f"python list size = {sys.getsizeof(py_list) * len(py_list)} bytes")

print(f"python list size = {np_arr.nbytes} bytes")


python list size = 80000005600000000 bytes
python list size = 800000000 bytes


2

In [17]:
#creating array
arr = np.array([1,2,3,4,5,6])
print(arr, type(arr), arr.shape)

arr2 = np.array([1,2,3,4,5, "prime"])
print(arr2, type(arr2), arr2.dtype, arr2.shape)

arr3 = np.array([ [1,2], [4,5], [7,8]])
print(arr3, type(arr3), arr3.dtype, arr3.shape)

[1 2 3 4 5 6] <class 'numpy.ndarray'> (6,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21 (6,)
[[1 2]
 [4 5]
 [7 8]] <class 'numpy.ndarray'> int64 (3, 2)


In [36]:
#creating array from 
arr1 = np.zeros((3,3), dtype = "int64")
print(arr1, arr1.shape)

arr2 = np.ones((2,3), dtype = "int64")
print(arr2, arr2.shape)

arr3 = np.full((3,4), 100)
print(arr3, arr3.shape)

arr4 = np.eye(3, dtype = "int64")
print(arr4, arr4.shape)

arr5 = np.arange(0,11,2)
print(arr5, arr5.shape)

arr6 = np.linspace(1,100,3, dtype = "int64")
print(arr6, arr6.shape)

[[0 0 0]
 [0 0 0]
 [0 0 0]] (3, 3)
[[1 1 1]
 [1 1 1]] (2, 3)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1 0 0]
 [0 1 0]
 [0 0 1]] (3, 3)
[ 0  2  4  6  8 10] (6,)
[  1  50 100] (3,)


In [40]:
arr = np.array([1,2,3,4,5,6])

print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.nbytes)
print(arr.ndim)

flr_arr = arr.astype(np.float64)
print(flr_arr, flr_arr.dtype)

(6,)
6
int64
48
1
[1. 2. 3. 4. 5. 6.] float64


In [9]:
arr = np.array([[1,2],[3,4],[5,6]])

print(arr, arr.shape)

reshaped = arr.reshape((2,3))

print(reshaped, reshaped.shape)

flat = arr.flatten()
print(flat, flat.shape)

[[1 2]
 [3 4]
 [5 6]] (3, 2)
[[1 2 3]
 [4 5 6]] (2, 3)
[1 2 3 4 5 6] (6,)


In [11]:
idx = [[1,0],[1,1], [0,0]]
print(arr[idx])

[[[3 4]
  [1 2]]

 [[3 4]
  [3 4]]

 [[1 2]
  [1 2]]]


In [14]:
#copy
arr = [1,2,3,4]
sub_arr = arr[:3]

print(arr)
print(sub_arr)

sub_arr[0] = 100
print(arr)
print(sub_arr)

#copy
arr1 = np.array([1,2,3,4,5])
sub_arr1 = arr1[:3].copy()

#view
#sub_arr1 = arr1[:3]

print(arr1)
print(sub_arr1)

sub_arr1[0] = 100
print(arr1)
print(sub_arr1)


[1, 2, 3, 4]
[1, 2, 3]
[1, 2, 3, 4]
[100, 2, 3]
[1 2 3 4 5]
[1 2 3]
[1 2 3 4 5]
[100   2   3]


In [5]:
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.sum(arr2D))

row_sum = np.sum(arr2D, axis = 0)
print(row_sum)

clm_sum = np.sum(arr2D, axis = 1)
print(clm_sum)

print(arr2D[0:2,1:2])

45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [11]:
arr3D = np.array([[[1,2], [3,4], [5,6]],[ [7,8], [9,10], [11,12]]])
print(arr3D, arr3D.shape)

print(arr3D[1,2,1])

first_row = arr3D[:, 0, :]
print(first_row)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
12
[[1 2]
 [7 8]]


In [13]:
#vectotization

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,3,4,5])
print(arr1 + arr2)

#broadcasting

print(arr1 + 5)

[ 2  4  6  8 10]
[ 6  7  8  9 10]


In [16]:
#normaliztion
arr = np.array([[1,2],[3,4]])

mean = np.mean(arr)
std_dev = np.std(arr)

nrm_arr = (arr-mean)/std_dev
print(nrm_arr)


[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


In [3]:
arr = np.array([1,2,3,4,5,6])

print(np.sum(arr))
print(np.prod(arr))
print(np.argmax(arr))
print(np.argmin(arr))

print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))

21
720
5
0
3.5
3.5
1.707825127659933
